/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/buildin examplees/AppFooter.vue')['default']
    Avatar: typeof import('./components/profile-card/profile-avatar.vue')['default']
    Header: typeof import('./components/app-header/page-header.vue')['default']
    HelloWorld: typeof import('./components/buildin examplees/HelloWorld.vue')['default']
    HorarioMarcado: typeof import('./components/profile-card/horario-marcado.vue')['default']
    MarcarHorario: typeof import('./components/profile-card/marcar-horario.vue')['default']
    PageHeader: typeof import('./components/app-header/page-header.vue')['default']
    ProfileAvatar: typeof import('./components/profile-card/profile-avatar.vue')['default']
    ProfileCardHeader: typeof import('./components/profile-card/profile-card-header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
