/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/buildin examplees/AppFooter.vue')['default']
    copy: typeof import('./components/profile-card/login/login-socials.vue')['default']
    HelloWorld: typeof import('./components/buildin examplees/HelloWorld.vue')['default']
    HorarioMarcado: typeof import('./components/profile-card/index/horario-marcado.vue')['default']
    HorariosPassados: typeof import('./components/profile-card/index/horarios-passados.vue')['default']
    LoginForm: typeof import('./components/profile-card/login/login-form.vue')['default']
    LoginSocials: typeof import('./components/profile-card/login/login-socials.vue')['default']
    MarcarHorario: typeof import('./components/profile-card/index/marcar-horario.vue')['default']
    PageHeader: typeof import('./components/app-header/page-header.vue')['default']
    ProfileAvatar: typeof import('./components/profile-card/profile-avatar.vue')['default']
    ProfileCardHeader: typeof import('./components/profile-card/profile-card-header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
