/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAcoes: typeof import('./components/profile-card/index/admin/admin-acoes.vue')['default']
    AdminHorarioMarcado: typeof import('./components/profile-card/index/admin/admin-horario-marcado.vue')['default']
    AppFooter: typeof import('./components/buildin examplees/AppFooter.vue')['default']
    CardCronograma: typeof import('./components/board/index/admin/cards-cronograma.vue')['default']
    CardsCronograma: typeof import('./components/board/index/admin/cards-cronograma.vue')['default']
    ClienteHorarioMarcado: typeof import('./components/profile-card/index/cliente/cliente-horario-marcado.vue')['default']
    ClienteHorariosPassados: typeof import('./components/profile-card/index/cliente/cliente-horarios-passados.vue')['default']
    ClienteMarcarHorario: typeof import('./components/profile-card/index/cliente/cliente-marcar-horario.vue')['default']
    Configs: typeof import('./components/board/index/admin/configs.vue')['default']
    copy: typeof import('./components/board/index/admin/configs copy.vue')['default']
    Cronograma: typeof import('./components/board/index/admin/cronograma.vue')['default']
    Excessoes: typeof import('./components/board/index/admin/excessoes.vue')['default']
    HelloWorld: typeof import('./components/buildin examplees/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/profile-card/login/login-form.vue')['default']
    LoginSocials: typeof import('./components/profile-card/login/login-socials.vue')['default']
    PageHeader: typeof import('./components/app-header/page-header.vue')['default']
    ProfileAvatar: typeof import('./components/profile-card/profile-avatar.vue')['default']
    ProfileCardHeader: typeof import('./components/profile-card/profile-card-header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewHorarioAdminBoard: typeof import('./views/horario/board/view-horario-admin-board.vue')['default']
    ViewHorarioAdminCard: typeof import('./views/horario/card/view-horario-admin-card.vue')['default']
    ViewHorarioClienteBoard: typeof import('./views/horario/board/view-horario-cliente-board.vue')['default']
    ViewHorarioClienteCard: typeof import('./views/horario/card/view-horario-cliente-card.vue')['default']
    ViewIndexAdminBoard: typeof import('./views/index/board/view-index-admin-board.vue')['default']
    ViewIndexAdminCard: typeof import('./views/index/card/view-index-admin-card.vue')['default']
    ViewIndexClienteBoard: typeof import('./views/index/board/view-index-cliente-board.vue')['default']
    ViewIndexClienteCard: typeof import('./views/index/card/view-index-cliente-card.vue')['default']
  }
}
